#!/bin/bash

sudo -v

# Automatically generate `fix_config.h`
OUTPUT="include/fix_config.h"
[ -f "$OUTPUT" ] && rm "$OUTPUT"

echo "#ifndef SUFS_FIX_CONFIG_H_" > "$OUTPUT"
echo "#define SUFS_FIX_CONFIG_H_" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "// Auto-generated by generate_fix_config.sh" >> "$OUTPUT"

for arg in "$@"; do
    case "$arg" in
        FIX_ALL)
            echo "#define FIX_CS_COUNTER 1" >> "$OUTPUT"
            echo "#define FIX_DRAM_PM_SYNC 1" >> "$OUTPUT"
            echo "#define FIX_RENAME 1" >> "$OUTPUT"
            echo "#define FIX_FLUSH 1" >> "$OUTPUT"
            ;;
        FIX_CS_COUNTER)
            echo "#define FIX_CS_COUNTER 1" >> "$OUTPUT"
            ;;
        FIX_DRAM_PM_SYNC)
            echo "#define FIX_DRAM_PM_SYNC 1" >> "$OUTPUT"
            ;;
        FIX_RENAME)
            echo "#define FIX_RENAME 1" >> "$OUTPUT"
            ;;
        FIX_FLUSH)
            echo "#define FIX_FLUSH 1" >> "$OUTPUT"
            ;;
    esac
done

echo "" >> "$OUTPUT"
echo "#endif // SUFS_FIX_CONFIG_H_" >> "$OUTPUT"

echo "$OUTPUT generated with args: $@"


# Compiles each component of ArckFS
subdirs=(kfs libfs libfsfd libfskv fsutils)

for i in ${subdirs[@]}
do 
    cd $i
    make clean && make -j && make install
    ret=$?
    cd -

    if [ $ret -eq 0 ]
    then
        echo "$i installed successfully!"
    else 
        echo "$i not installed!"
        exit 1
    fi 
done  

echo "ArckFS installed successfully!"


